# Generated by Django 3.2.20 on 2023-08-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('photo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('CATEGORY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('WORKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('SERVICE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.service')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('BILL', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.bill')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_point', models.IntegerField()),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_date', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('reply_date', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('chat', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('SERVICE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.service')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='BOOKING',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.bookings'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_no', models.IntegerField()),
                ('IFSC_code', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.user')),
            ],
        ),
    ]
