# Generated by Django 3.2.20 on 2023-08-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_getme_help_app', '0003_auto_20230808_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='SERVICE',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='USER',
        ),
        migrations.AddField(
            model_name='rating',
            name='BOOKINGS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.bookings'),
        ),
    ]
