# Generated by Django 3.2.20 on 2023-08-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_getme_help_app', '0005_auto_20230810_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
