# Generated by Django 3.2.20 on 2023-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_getme_help_app', '0006_rename_total_amount_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
