# Generated by Django 3.2.20 on 2023-08-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_getme_help_app', '0007_auto_20230810_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_no',
            field=models.BigIntegerField(),
        ),
    ]
