# Generated by Django 3.2.20 on 2023-08-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_getme_help_app', '0008_alter_bank_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='USER',
        ),
        migrations.AddField(
            model_name='bank',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.login'),
        ),
    ]
