# Generated by Django 3.2.20 on 2023-08-21 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_getme_help_app', '0009_auto_20230819_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_point',
            name='USER',
        ),
        migrations.AddField(
            model_name='credit_point',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_getme_help_app.login'),
        ),
    ]
